apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-to-outside-namespaces
  namespace: airbyte
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # Izinkan komunikasi dalam namespace airbyte
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: airbyte

    # Izinkan komunikasi ke kube-system hanya untuk DNS (port 53 TCP)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: TCP

    # Izinkan akses ke luar hanya untuk port 22, 443, dan 80
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 22
          protocol: TCP
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
